---
# tasks/playbook_retrieve_facts_vms.yaml
# Author: Micah Bronfman
# Purpose: Get VM Information
- name: "Add VMs to CloudVMs group with their private IPs"
  add_host:
    name: "vm{{ item_index + 1 }}"
    groups: CloudVMs
    ansible_host: "{{ item.server.addresses['CH-822922-net'][0]['addr'] | default('No IP Found') }}"
  loop: "{{ vm_info.results }}"
  loop_control:
    index_var: item_index

- name: "Save Master Cloud"
  add_host:
    name: "vm1"
    groups: MasterVM
    ansible_host: "{{ vm_info.results[0].server.addresses['CH-822922-net'][0]['addr'] | default('No IP Found') }}"
